// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT9hlU1rRG-xvM75qN0erykGpUy1XQBgg',
    appId: '1:842401490441:web:6414b793f5142dbe4ebad8',
    messagingSenderId: '842401490441',
    projectId: 'flutter-firebase-kurulumu-v1',
    authDomain: 'flutter-firebase-kurulumu-v1.firebaseapp.com',
    storageBucket: 'flutter-firebase-kurulumu-v1.appspot.com',
    measurementId: 'G-BKYXQW2RRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-hoa42opHeLfFj8VOZCuwBFkuRjlgdh8',
    appId: '1:842401490441:android:13ffebddda4a5e344ebad8',
    messagingSenderId: '842401490441',
    projectId: 'flutter-firebase-kurulumu-v1',
    storageBucket: 'flutter-firebase-kurulumu-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdyMfmLUYS1Mhe8bTASYEeZ1SlRFRZjws',
    appId: '1:842401490441:ios:e282e3fe7913d74d4ebad8',
    messagingSenderId: '842401490441',
    projectId: 'flutter-firebase-kurulumu-v1',
    storageBucket: 'flutter-firebase-kurulumu-v1.appspot.com',
    iosClientId: '842401490441-unp55c28ld1iqm3v0lcj23hr0da0hc2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseKurulumu',
  );
}
